const hotels = [
  {
    image: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg", // Replace with a relevant hotel image URL from Pexels
    name: "Regency Sameera Vellore by GRT Hotels",
    location: "Vellore, Tamil Nadu",
    description: "A premium hotel with modern amenities and excellent service.",
    rating: 4.5,
    priceRange: "$100 - $150",
  },
  {
    image: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg", // Replace with another hotel image URL
    name: "Hotel Rangalaya Royal",
    location: "Vellore, Tamil Nadu",
    description: "A luxurious hotel offering comfort and elegance for guests.",
    rating: 4.3,
    priceRange: "$90 - $140",
  },
  {
    image: "https://images.pexels.com/photos/169190/pexels-photo-169190.jpeg",
    name: "Fortune Park Vellore",
    location: "Vellore, Tamil Nadu",
    description: "Located near popular attractions, offering quality stay.",
    rating: 4.4,
    priceRange: "$110 - $160",
  },
  {
    image: "https://images.pexels.com/photos/261187/pexels-photo-261187.jpeg",
    name: "Poppys Anukula Residency",
    location: "Vellore, Tamil Nadu",
    description: "Affordable and comfortable stay with friendly service.",
    rating: 4.0,
    priceRange: "$60 - $100",
  },
  {
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    name: "Darling Residency",
    location: "Vellore, Tamil Nadu",
    description: "A well-maintained hotel with a range of amenities.",
    rating: 4.1,
    priceRange: "$80 - $120",
  },
  {
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
    name: "Khanna Fiesta",
    location: "Vellore, Tamil Nadu",
    description: "Offers comfortable rooms and great service for guests.",
    rating: 4.0,
    priceRange: "$70 - $110",
  },
  {
    image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
    name: "Grand Krishna",
    location: "Vellore, Tamil Nadu",
    description: "A top choice for both leisure and business travelers.",
    rating: 4.2,
    priceRange: "$85 - $130",
  },
  {
    image: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
    name: "Baby Residency",
    location: "Vellore, Tamil Nadu",
    description: "Budget-friendly hotel with basic amenities.",
    rating: 3.8,
    priceRange: "$40 - $70",
  },
  {
    image: "https://images.pexels.com/photos/244133/pexels-photo-244133.jpeg",
    name: "Hotel SMS Grand Inn",
    location: "Vellore, Tamil Nadu",
    description: "Known for its excellent hospitality and strategic location.",
    rating: 4.1,
    priceRange: "$75 - $110",
  },
  {
    image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    name: "Sri Annamalaiyar Residency",
    location: "Vellore, Tamil Nadu",
    description: "Comfortable rooms with good accessibility to city spots.",
    rating: 3.9,
    priceRange: "$50 - $90",
  },
  {
    image: "https://images.pexels.com/photos/261436/pexels-photo-261436.jpeg",
    name: "Hotel Palm Tree",
    location: "Vellore, Tamil Nadu",
    description: "Offers spacious rooms and friendly service.",
    rating: 4.0,
    priceRange: "$65 - $100",
  },
  {
    image: "https://images.pexels.com/photos/258804/pexels-photo-258804.jpeg",
    name: "Siva AVM Grande",
    location: "Vellore, Tamil Nadu",
    description: "Affordable stay with all basic facilities.",
    rating: 3.7,
    priceRange: "$45 - $80",
  },
  {
    image: "https://images.pexels.com/photos/261421/pexels-photo-261421.jpeg",
    name: "Hotel Mount Paradise",
    location: "Vellore, Tamil Nadu",
    description: "Located near scenic spots and offering cozy rooms.",
    rating: 4.0,
    priceRange: "$60 - $95",
  },
  {
    image: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg",
    name: "Hotel Surabi International",
    location: "Vellore, Tamil Nadu",
    description: "Popular for business stays and easy city access.",
    rating: 4.2,
    priceRange: "$70 - $110",
  },
  {
    image: "https://images.pexels.com/photos/256423/pexels-photo-256423.jpeg",
    name: "Rangalaya Royal",
    location: "Vellore, Tamil Nadu",
    description: "A well-reviewed hotel known for great service.",
    rating: 4.4,
    priceRange: "$90 - $140",
  },
  {
    image: "https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg",
    name: "Hotel GeeKay Millennia",
    location: "Vellore, Tamil Nadu",
    description: "Modern hotel with quality amenities for business travelers.",
    rating: 4.3,
    priceRange: "$100 - $150",
  },
  {
    image: "https://images.pexels.com/photos/260931/pexels-photo-260931.jpeg",
    name: "Hotel Hills",
    location: "Vellore, Tamil Nadu",
    description: "Ideal for travelers looking for tranquility.",
    rating: 4.1,
    priceRange: "$60 - $100",
  },
  {
    image: "https://images.pexels.com/photos/261436/pexels-photo-261436.jpeg",
    name: "Hotel Aavanaa Inn",
    location: "Vellore, Tamil Nadu",
    description: "Simple and clean hotel with all the basic amenities.",
    rating: 3.8,
    priceRange: "$50 - $85",
  },
  {
    image: "https://images.pexels.com/photos/262218/pexels-photo-262218.jpeg",
    name: "Hotel River View",
    location: "Vellore, Tamil Nadu",
    description: "Offers scenic views and pleasant accommodation.",
    rating: 4.0,
    priceRange: "$70 - $120",
  },
  {
    image: "https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg",
    name: "Hotel Metro Park",
    location: "Vellore, Tamil Nadu",
    description: "A budget-friendly option for travelers.",
    rating: 3.9,
    priceRange: "$55 - $90",
  },
];

export default hotels;
